name: 'Deploy'
description: 'Greet someone and record the time'
inputs:
  output-directory:
    description: 'Place where to put the new website data (relative to GITHUB_WORKSPACE)'
    required: true
  gitlab-url:
    description: 'URL of the gitlab where to get data'
    required: true
  project-name:
    description: 'Name of the project on the gitlab (urlencoded)'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.output-directory }}
    - ${{ inputs.gitlab-url }}
    - ${{ inputs.project-name }} 
