var namespacePDI =
[
    [ "Array_datatype", "classPDI_1_1Array__datatype.html", "classPDI_1_1Array__datatype" ],
    [ "Callbacks", "classPDI_1_1Callbacks.html", "classPDI_1_1Callbacks" ],
    [ "Config_error", "structPDI_1_1Config__error.html", "structPDI_1_1Config__error" ],
    [ "Context", "classPDI_1_1Context.html", "classPDI_1_1Context" ],
    [ "Context_proxy", "classPDI_1_1Context__proxy.html", "classPDI_1_1Context__proxy" ],
    [ "Data_descriptor", "classPDI_1_1Data__descriptor.html", "classPDI_1_1Data__descriptor" ],
    [ "Datatype", "classPDI_1_1Datatype.html", "classPDI_1_1Datatype" ],
    [ "Datatype_template", "classPDI_1_1Datatype__template.html", "classPDI_1_1Datatype__template" ],
    [ "Error", "classPDI_1_1Error.html", "classPDI_1_1Error" ],
    [ "Expression", "classPDI_1_1Expression.html", "classPDI_1_1Expression" ],
    [ "Impl_error", "structPDI_1_1Impl__error.html", "structPDI_1_1Impl__error" ],
    [ "Paraconf_wrapper", "structPDI_1_1Paraconf__wrapper.html", "structPDI_1_1Paraconf__wrapper" ],
    [ "Plugin", "classPDI_1_1Plugin.html", "classPDI_1_1Plugin" ],
    [ "Plugin_error", "structPDI_1_1Plugin__error.html", "structPDI_1_1Plugin__error" ],
    [ "Pointer_datatype", "classPDI_1_1Pointer__datatype.html", "classPDI_1_1Pointer__datatype" ],
    [ "Record_datatype", "classPDI_1_1Record__datatype.html", "classPDI_1_1Record__datatype" ],
    [ "Ref_any", "classPDI_1_1Ref__any.html", "classPDI_1_1Ref__any" ],
    [ "Reference_base", "classPDI_1_1Reference__base.html", "classPDI_1_1Reference__base" ],
    [ "Right_error", "structPDI_1_1Right__error.html", "structPDI_1_1Right__error" ],
    [ "Scalar_datatype", "classPDI_1_1Scalar__datatype.html", "classPDI_1_1Scalar__datatype" ],
    [ "State_error", "structPDI_1_1State__error.html", "structPDI_1_1State__error" ],
    [ "System_error", "structPDI_1_1System__error.html", "structPDI_1_1System__error" ],
    [ "Type_error", "structPDI_1_1Type__error.html", "structPDI_1_1Type__error" ],
    [ "Unavailable_error", "structPDI_1_1Unavailable__error.html", "structPDI_1_1Unavailable__error" ],
    [ "Value_error", "structPDI_1_1Value__error.html", "structPDI_1_1Value__error" ]
];