name: Deploy
on:
  repository_dispatch: ~
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v2
    - name: Clean previous
      run: |
        rm -rf *
    - name: Build site
      uses: pdidev/pdidev.github.io/.github/actions/deploy@master
      with:
        output-directory: .
        gitlab-url:  https://gitlab.maisondelasimulation.fr
        project-name:  pdidev%2Fpdi
    - name: Add CNAME
      run: |
        echo pdi.julien-bigot.fr > CNAME
        echo "google-site-verification: googleb7e4372583e95220.html" > googleb7e4372583e95220.html
    - name: Push
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@noreply.example.com"
        git add -A .
        git commit --allow-empty -m "New version deployed by ${GITHUB_EVENT_NAME} ${GITHUB_RUN_NUMBER}"
        git push -f
